### ISSUE TITLE
tough-cookie not found

### ISSUE THREAD

**Issue by atul-shimpi** [salesforce/tough-cookie#104] opened 2017-10-18 11:00 UTC
Hello,
I have installed touch-cookie. Checked if its present in node_modules.
However, when i start my app, node is complaining tha that touch-cookie not found.

**Comment by inikulin** [comment] 2017-10-18 11:55
It's hard to make any assumptions without reproduction code. Closing for now due to the insufficient information. Will be happy to reopen once reproduction code will be provided.

**Closed by inikulin** 2017-10-18 11:55 UTC
