### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by samislam** [salesforce/tough-cookie#348] opened 2023-12-20 15:45 UTC
I am running Nodejs version v21.4.0, and when starting my app, I see this warning.

Are there any plans to replace `punycode` with another solution to hide this warning message?

punycode v4.1.3

**Comment by wjhsf** [comment] 2023-12-20 16:59
Duplicate of #315, #324, #338. Fixed by #346.

**Closed by wjhsf** 2023-12-20 16:59 UTC
