### ISSUE TITLE
sameSite has no effect

### ISSUE THREAD

**Issue by gajus** [salesforce/tough-cookie#182] opened 2020-02-16 05:06 UTC
```js
console.log((new Cookie({
  key: 'foo',
  value: 'bar',
  sameSite: 'strict'
})).toJSON());

// { key: 'foo', value: 'bar', creation: '2020-02-16T05:05:14.018Z' }

```

```js
console.log((new Cookie({
  key: 'foo',
  value: 'bar',
  sameSite: 'strict'
})).toString());

// foo=bar

```

**Comment by awaterma** [comment] 2020-03-06 00:22
Is this against our current version (3.0.1)? or master?

**Comment by neg3ntropy** [comment] 2020-03-06 08:41
3.0.1 fails.

Can you put out a release with this ASAP? It has become critical by now.

**Comment by flotwig** [comment] 2020-03-19 18:40
+1, where is the release with Samesite support? @ShivanKaul's commit to add support was merged in October: https://github.com/salesforce/tough-cookie/commit/553ccdafb8d383d4043f5d28768be2928d02062c

**Comment by awaterma** [comment] 2020-03-19 18:45
It's in process. I should be able to do a push to NPM today or tomorrow. 

Sorry for the delay; I live and work in Seattle, Washington. It's been difficult to keep focused; especially on volunteer efforts.

**Comment by flotwig** [comment] 2020-03-19 18:48
@awaterma Absolutely, no worries, I did not mean to come across as impatient :smile:  Thank you for the update & for all the work you're doing on this lib.

**Comment by awaterma** [comment] 2020-03-19 18:52
We're very excited about the update, and i'm glad you are too! I apologize for the delay, and thank you for your understanding!

**Comment by awaterma** [comment] 2020-04-07 16:22
@flotwig -- have you been able to confirm that 4.0.0 is working for you on this issue? Please let us know; I'd like to pull some issues onto our project plan for 4.0.1.

**Comment by flotwig** [comment] 2020-04-07 18:16
@awaterma `sameSite` is working as expected for us on tough-cookie@4.0.0 :+1:

**Comment by awaterma** [comment] 2020-04-20 18:11
We will add a regression test for this issue, and then close.

**Comment by ruoho** [comment] 2020-05-18 16:59
Looks like @ShivanKaul already had put some good tests in
https://github.com/salesforce/tough-cookie/commit/553ccdafb8d383d4043f5d28768be2928d02062c#diff-028dbfa60a0c655c760e8d25150d4ca6R231

**Closed** 2020-07-20 21:45 UTC
