### ISSUE TITLE
Remove psl from dependency

### ISSUE THREAD

**Issue by amicus-veritatis** [salesforce/tough-cookie#352] opened 2024-01-02 09:48 UTC
After reviewing the repository and the maintainer's github profile, It appears that yhe `psl` is de facto deprecated, with [the issue](https://github.com/lupomontero/psl/issues/296) remaining open for two years.

Considering that large project, for example `jsdom` and even python packages (e.g. [readabilipy](https://github.com/alan-turing-institute/ReadabiliPy)) depend on this package, it seems appropriate to remove the de facto deprecated `psl` package from dependencies and replace it with any other alternative package.

**Comment by wjhsf** [comment] 2024-01-02 15:06
Duplicate of #338, fixed in #346. Please search existing issues before creating new ones.

**Closed by wjhsf** 2024-01-02 15:06 UTC
